This patch was developed in-house and has been submitted upstream:
http://bugs.python.org/issue23584

--- Python-2.7.9/Lib/test/test_doctest.py.~1~	2015-02-27 13:14:35.000000000 -0800
+++ Python-2.7.9/Lib/test/test_doctest.py	2015-03-04 08:19:15.863620533 -0800
@@ -2581,7 +2581,7 @@
     >>> import tempfile, os
     >>> fn = tempfile.mktemp()
     >>> open(fn, 'w').write('Test:\r\n\r\n  >>> x = 1 + 1\r\n\r\nDone.\r\n')
-    >>> doctest.testfile(fn, False)
+    >>> doctest.testfile(fn, False, verbose=False)
     TestResults(failed=0, attempted=1)
     >>> os.remove(fn)
 
@@ -2589,7 +2589,7 @@
 
     >>> fn = tempfile.mktemp()
     >>> open(fn, 'w').write('Test:\n\n  >>> x = 1 + 1\n\nDone.\n')
-    >>> doctest.testfile(fn, False)
+    >>> doctest.testfile(fn, False, verbose=False)
     TestResults(failed=0, attempted=1)
     >>> os.remove(fn)
 
